on:
  workflow_dispatch:
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Use the token
        uses:  actions/checkout@v3.6.0
        with: 
          repository: https://github.com/Dedac-Emu-Org/congenial-octo-doodle
          token : ${{ steps.generate_token.outputs.token }}
      
